version: "3.8"

services:
  api-gateway:
    build:
      context: ./api_gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - app-network
      - service-network
    depends_on:
      - recipe-service
      - auth-service
      - machine-service
      - resource-service
      - planning-service
      - reporting-service

  recipe-service:
    build:
      context: ./recipe_management_service
    container_name: recipe-service
    expose:
      - "8081"
    networks:
      - service-network
    depends_on:
      mysql-recipe:
        condition: service_healthy
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-recipe:3306/recipes
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect

  mysql-recipe:
    image: mysql:8.0
    container_name: mysql-recipe
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: recipes
    networks:
      - service-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  auth-service:
    build:
      context: ./auth_service
    container_name: auth-service
    expose:
      - "8083"
    networks:
      - service-network
    depends_on:
      mysql-auth:
        condition: service_healthy
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-auth:3306/users
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect

  mysql-auth:
    image: mysql:8.0
    container_name: mysql-auth
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: users
    networks:
      - service-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  machine-service:
    build:
      context: ./machine_service
    container_name: machine-service
    expose:
      - "8082"
    networks:
      - service-network
    depends_on:
      mysql-machine:
        condition: service_healthy
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-machine:3306/machines
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect

  mysql-machine:
    image: mysql:8.0
    container_name: mysql-machine
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: machines
    networks:
      - service-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  resource-service:
    build:
      context: ./resource_service
    container_name: resource-service
    expose:
      - "8084"
    networks:
      - service-network
    depends_on:
      mysql-resource:
        condition: service_healthy
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-resource:3306/resources
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect

  mysql-resource:
    image: mysql:8.0
    container_name: mysql-resource
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: resources
    networks:
      - service-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  planning-service:
    build:
      context: ./planning_service
    container_name: planning-service
    expose:
      - "8085"
    networks:
      - service-network
    depends_on:
      mysql-planning:
        condition: service_healthy
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-planning:3306/planning
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect

  mysql-planning:
    image: mysql:8.0
    container_name: mysql-planning
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: planning
    networks:
      - service-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  reporting-service:
    build:
      context: ./reporting_service
    container_name: reporting-service
    expose:
      - "8086"
    networks:
      - service-network
    restart: always

networks:
  app-network:
    driver: bridge
  service-network:
    driver: bridge
